name = "pevensie_postgres"
version = "1.1.0"
description = "The official Postgres driver for the Pevensie framework"
licences = ["MIT"]
repository = { type = "github", user = "Pevensie", repo = "pevensie_postgres" }
links = [{ title = "Website", href = "https://pevensie.dev" }]
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
pevensie = ">= 1.1.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
filepath = ">= 1.1.0 and < 2.0.0"
gtempo = ">= 7.2.2 and < 8.0.0"
gleam_crypto = ">= 1.4.0 and < 2.0.0"
pog = ">= 3.1.0 and < 4.0.0"
glint = ">= 1.1.1 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
snag = ">= 1.1.0 and < 2.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
